### ISSUE TITLE
Snow Puddles

### ISSUE THREAD

**Issue by Silvrus** [mc-jt9/Puddles#2]
Not so much a bug as merely a graphical glitch. Snow creates puddles, then subsequent snowfall covers the puddle, but hovers over the puddle as if on a full block.

**Comment by Pentasis** [comment]
I noticed this too, here's a screenshot that shows the bug.

![2019-01-26_12 55 17](https://user-images.githubusercontent.com/7046024/51786817-1be8c380-216a-11e9-86e0-e11c6ca6fc5a.png)

**Comment by OrderedChaos-Dev** [comment]
Huh, I didn't think of that happening. I thought I disabled puddles for snowfall.
