### ISSUE TITLE
Frame rate drops when mod is installed

### ISSUE THREAD

**Issue by AngleWyrm10** [mc-jt9/Puddles#7]
From 35-40 fps down to 15-20 fps.
I believe the culprit is this long search process:
https://github.com/OrderedChaos-Dev/Puddles/blob/6f71b0265349a0eee02ebe46e99b23f46effc74b/src/main/java/puddles/Puddles.java#L112

---
[Tom's Hardware review of my computer](https://www.tomsguide.com/us/alienware-aurora-r7,review-4889.html), Jan 28, 2019

**Comment by OrderedChaos-Dev** [comment]
Cannot reproduce, getting smooth 60 fps. The iterator loop is not actually very taxing on memory.
