### ISSUE TITLE
 If you pour water from a bucket on a puddle, it will fall out.

### ISSUE THREAD

**Issue by Exzept1on** [mc-jt9/Puddles#9]
[1.12.2]
If you pour water from a bucket on a puddle, it will fall out.

**Comment by OrderedChaos-Dev** [comment]
1.12 is not supported

**Comment by Exzept1on** [comment]
It's easy to say that the version is not supported, but it's quite another thing to take and fix old bugs.

**Comment by OrderedChaos-Dev** [comment]
This bug doesn't exist in more recent versions, and I don't have time to jump back and forth between 1.12, 1.16, and 1.18.

**Comment by Exzept1on** [comment]
OK, I get it, thanks for the answer.
